# SERVER
SERVER_NAME: MWeiBo
SERVER_RUNMODE: debug
SERVER_Port: :8080
SERVER_URL: http://localhost:8080 # 网站 url，内部跳转时会用到该项
SERVER_KEY: base64:O+VQ74YEigLPDzLKnh2HW/yjCdU2ON9v7xuKBgSOEAo=
SERVER_SessionKey: MWeiBoSession
SERVER_ContextUserKey: CurrentUserData
SERVER_StaticPath: static
SERVER_ViewsPath: views
SERVER_EnableCsrf: true
SERVER_CsrfParamName: _csrf
SERVER_CsrfHeaderName: X-CsrfToken

# DB
DB_TYPE: mysql
DB_HOST: 127.0.0.1
DB_PORT: 3306
DB_NAME: mweibo
DB_USER: root
DB_PASSWORD: 123456

# MAIL
MAIL_DRIVER: smtp
MAIL_HOST: smtp.qq.com 
MAIL_PORT: 465 
MAIL_USERNAME: 184322994@qq.com
MAIL_PASSWORD: ****** # 授权码或密码
MAIL_SENDER: MWeiBo # 邮件发送者名称

page_size: 5

public: static

dsn: root:123456@tcp(127.0.0.1:3306)/wangchunguang?charset=utf8&parseTime=True&loc=Local
